### PR TITLE
implemented multiple keys and fixed a critical bug for MR

### PR DESCRIPTION
**Pull request by deukyeon**
This PR Fixes DICL/EclipseMETA#86

Once I commented out some lines, please let me know if it should be removed.

Checklist
- [ ] Follows Google Coding Style.
- [ ] At least one reviewer approved (for non-trivial changes).

---

### CODE REVIEW

**Comment by vicentebolea** [comment]
Hey Ill check it soon :+1:

**Comment by deukyeon** [comment]
@vicentebolea yup! Let's talk about this pull request later :)

**Comment by vicentebolea** [comment]
Hey i am having some problems running the mapreduce in this branch, some of the node dies when I run it

**Review by vicentebolea — APPROVED** [review]
LGTM :+1: Already edited

**Pull request merged**
